
service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: 'arn:aws:s3:::uploaded-shop'
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::uploaded-shop/*'
        - Effect: Allow
          Action: "sqs:*"
          Resource: 'arn:aws:sqs:eu-west-1:833686642500:catalogItemsQueue'

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: import/{name}
          method: get
          request:
            parameters:
              paths:
                name: true
          cors:
            origin: '*'
            headers: '*'
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: uploaded-shop
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true